### PR TITLE
welcome.md page

### PR DESCRIPTION
**Pull request by rueckstiess**
@kangas, @imlucas how's this? 

[Review on Reviewable](https://reviewable.io/reviews/mongodb-js/mongodb-js.github.io/14)

### CODE REVIEW

**Comment by rueckstiess** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14)

---

<sup>**[docs/welcome.md, line 64 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiHJWnCLyD_r-TS3n7)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L64)):</sup>
these 3 links need to be fixed. for now, we can link to the files in mongodb-js.github.io (this repo). Eventually, they should link to the empty template repo (for khaos).

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14)

---

<sup>**[docs/README.md, line 6 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiJLUT3Ti8qayuDeNO)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/README.md#L6)):</sup>
Looking at other patterns, this (`./docs/README.md`) should be merged into `./README.md`

---

<sup>**[docs/welcome.md, line 1 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiKB2eRZz97HrD1mk9)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L1)):</sup>
Move this to `./CONTRIBUTING.md`

---

<sup>**[docs/welcome.md, line 11 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiLJTJyIkkwr1GGBGf)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L11)):</sup>
This isn't quite right and is the most long running and painful problem in the community... See the [ubuntu.sh](https://gist.github.com/imlucas/c5e4e327feb2ee539034#file-ubuntu-sh) example.

Want to just have this be the once place all other repos can link back to so we can all stop writing this same description over and over again :) (See long rant in [this node-forward discussion](https://github.com/node-forward/help/issues/4#issuecomment-63337853) )

---

<sup>**[docs/welcome.md, line 31 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiXOXQoKjYeqYVbKlZ)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L31)):</sup>
Let's just farm this out to GitHub's knowledge base: https://help.github.com/articles/set-up-git/#setting-up-git

## 2. [Setup Git](https://help.github.com/articles/set-up-git/#setting-up-git)

---

<sup>**[docs/welcome.md, line 34 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiYTAlOcz7TVE2DZj-)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L34)):</sup>
We'll need to make another gitter room anybody can join because of some weird semantics (already have to be a member of the mongodb-js org to get to https://gitter.im/mongodb-js :()

---

<sup>**[docs/welcome.md, line 45 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiYmi77XZcpNmNEC5V)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L45)):</sup>
Hmm. Perhaps we should think about this a bit more.  Seeing it written up, I can only imagine how confusing this would be for new contributors...  If all apps will end up in the mongodb or 10gen org, mongodb-js is just micro-modules and we only need to mention that.

---

<sup>**[docs/welcome.md, line 49 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiZPpfgnWXIP3a7eA-)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L49)):</sup>
Could we explore what kind of notification options review tools like reviewable offer?  It's up to you to make a code review happen would cause me to respond as a contributor like "pfft I'm never doing code reviews then, brah.".

Curious to hear your thoughts on this.  Perhaps there is something we could do with all repos having at least two maintainers (also relates to who makes sure the build stays green, responds to issues etc).  Let's circle back to this though after letting it bake for a while though.

---

<sup>**[docs/welcome.md, line 64 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiHJWnCLyD_r-TS3n7)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L64)):</sup>
Can we just remove this for now and replace with @todo's?  Still under active discussion https://github.com/mongodb-js/mongodb-js.github.io/pull/8#discussion-diff-26481774

---

<sup>**[docs/welcome.md, line 67 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiNNTT_REu9kwrBIqS)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L67)):</sup>
This isn't quite right... @see https://github.com/10gen/mongoscope/blob/dev/docs/dev.md#sublime-text

Also think the complexity of explaining this/cognitive burden for new contributors is just too high not to automate it all.

---

**Comment by rueckstiess** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14)

---

<sup>**[docs/README.md, line 6 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiJLUT3Ti8qayuDeNO)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/README.md#L6)):</sup>
ok

---

<sup>**[docs/welcome.md, line 1 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiKB2eRZz97HrD1mk9)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L1)):</sup>
ok

---

<sup>**[docs/welcome.md, line 11 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiLJTJyIkkwr1GGBGf)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L11)):</sup>
Ok what is the right way to install? I hope it's not 

> "pipe this random script from the internet to your bash as root"

:)

---

<sup>**[docs/welcome.md, line 31 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiXOXQoKjYeqYVbKlZ)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L31)):</sup>
ok

---

<sup>**[docs/welcome.md, line 34 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiYTAlOcz7TVE2DZj-)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L34)):</sup>
speechless...

---

<sup>**[docs/welcome.md, line 45 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiYmi77XZcpNmNEC5V)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L45)):</sup>
But even for micro-modules (at what point does it become macro?), personally I'd prefer to have a _master_ and _dev_ branch. I just wanted to allow "master-only" for folks who really just want to put a single function in mongodb-js and be done with it. Allowing both is fine I think. 

What part do you find confusing? the nvie writeup? Or the text here?

---

<sup>**[docs/welcome.md, line 49 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiZPpfgnWXIP3a7eA-)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L49)):</sup>
Would be nice if reviewable solves this somehow. 

I mostly wanted to make clear that we put the changes directly in a feature branch on the repo (as discussed this morning), as opposed to a fork. 

How about I'll phrase the code review sentence like: 

> If you want a code review, ask on [gitter]() ...

---

<sup>**[docs/welcome.md, line 64 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiHJWnCLyD_r-TS3n7)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L64)):</sup>
ok, will remove these links for now.

---

<sup>**[docs/welcome.md, line 67 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiNNTT_REu9kwrBIqS)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L67)):</sup>
I picked a few from your list but not everything is required. I don't write coffeescript for example or intent to look at binary hex. Can't force all this stuff on everyone.

automating is fine, but knowledgable people might just want to add manually. once we have automation for this we can add a sentence like

> quick and easy way to get all these plugins is: `mj init --sublime`

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14)

---

<sup>**[docs/welcome.md, line 45 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiYmi77XZcpNmNEC5V)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L45)):</sup>
Confusing in terms of being a new contributor.  But I think github might solve this on their end: if you're using nvie's flow, you have `develop` as your default branch so all new PR's default to going to that branch.  Same goes if you have `master` as the default branch and using a different model than nvie's.  

Like style, perhaps we can leave this to repo owners and just say you need a  ./CONTRIBUTING.md file in your root (our templates will take care of this for new stuff) that says here's the branching model we use etc.  

> Asides 
> - [significance of calling it CONTRIBUTORS.md to GitHub](https://github.com/blog/1184-contributing-guidelines)
> - [why you need a CONTRIBUTORS.md](https://github.com/rafalchmiel/friction/wiki#contributing-guide-not-found)

---

<sup>**[docs/welcome.md, line 49 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiZPpfgnWXIP3a7eA-)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L49)):</sup>
Yep all sounds good.  Just connecting the dots from standup (on kernel team, getting your code reviewed is your responsibility) with other questions that have come up around maintainers (weird admin only GH settings woes, Issue Watch responsibilities, etc).

---

<sup>**[docs/welcome.md, line 67 [r1]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkiNNTT_REu9kwrBIqS)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/e51ef371407d5701013884703e77ac279edd7ba5/docs/welcome.md#L67)):</sup>
Good points.  Just one logic change then: 

```
If you use Sublime Text as your editor, you may find these plugins from [Sublime Package Control](https://packagecontrol.io/installation) useful:
```

---

<sup>**[README.md, line 3 [r2]](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14#-JkimPAiUKhn-nl5CTqZ)** ([raw file](https://github.com/mongodb-js/mongodb-js.github.io/blob/5b82c9df98d951c79e35839163c91a00613e329d/README.md#L3)):</sup>
Ah.  Much better!  Thanks!

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14)

Reviewed files:
- CONTRIBUTING.md @ r3
- docs/README.md @ r2
- docs/welcome.md @ r2
- README.md @ r2

---

**Comment by imlucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mongodb-js/mongodb-js.github.io/14)

Reviewed files:
- README.md @ r4

---

**Pull request merged**
